jar_name: "notification.jar"
conf_name: "application.yml"
app_path: "/opt/notification"
app_conf_path: "{{ app_path }}/conf"
app_bin_path: "{{ app_path }}/bin"
project_name: "notification"
systemd_script_name: "notification.service"