---
- hosts: auth
  become: yes
  remote_user: "{{ hostvars[groups['auth'][0]]['ansible_ssh_user'] }}"
  vars_files:
    - vars/config.yml
  tasks:
    - include: tasks/jvm_service.yml

- hosts: auth
  become: yes
  remote_user: "{{ hostvars[groups['auth'][0]]['ansible_ssh_user'] }}"
  vars_files:
    - vars/eureka.yml
  tasks:
    - include: tasks/jvm_service.yml

- hosts: auth
  become: yes
  remote_user: "{{ hostvars[groups['auth'][0]]['ansible_ssh_user'] }}"
  vars_files:
    - vars/auth.yml
  tasks:
    - include: tasks/jvm_service.yml

- hosts: notification
  become: yes
  remote_user: "{{ hostvars[groups['notification'][0]]['ansible_ssh_user'] }}"
  vars_files:
    - vars/notification.yml
  tasks:
    - include: tasks/jvm_service.yml
