spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  profiles:
     active: native

server:
  port: 8888

#security:
#  user:
#    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /var/log/config.log